
	<!-- start header -->
	<header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"><span>H</span>radla, <span>v</span>olty, <span>j</span>ednočipy</a>
                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">
                        <li[[index.html]]><a href="index.html">Úvod</a></li>
                        <li class="dropdown">
                            <a href="kniha.html" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Kniha <b class=" icon-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                <li[[obsah.html]]><a href="obsah.html">Obsah</a></li>
                                <li[[kniha.html]]><a href="kniha.html">Kde získat knihu?</a></li>
                                <li[[errata.html]]><a href="errata.html" >Errata</a></li>
                                <li><a href="//nic.cz">Vydavatel</a></li>
                                <li><a href="//github.com/elektrokniha">Zdrojové kódy</a></li>
                            </ul>
                        </li>    
                        <li[[parts.html]]><a href="parts.html">Součástky</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">Pomůcky <b class=" icon-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                <li[[simcir.html]]><a href="simcir.html">SimCir</a></li>
                                <li><a href="http://www.ohmslawcalculator.com/ohms-law-calculator">Kalkulačka pro Ohmův zákon</a></li>
								<li><a href="http://www.hobby-hour.com/electronics/ledcalc.php">Výpočet rezistoru k LED</a></li>
								<li><a href="http://www.calculatoredge.com/index.htm#electronics">Další online kalkulačky</a></li>
								<li><a href="http://www.schematics.com">Online kreslení schémat</a></li>

                            </ul>
                        </li>
                        <li><a href="circuitjs.html">Emulátor</a></li>
                        <li[[tipy.html]]><a href="tipy.html">Tipy</a></li>
                        <li><a href="//eknh.cz/forum">Diskuse</a></li>
                    </ul>
                </div>
            </div>
        </div>
	</header>
	<!-- end header -->
